version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=procom_admin
      - POSTGRESQL_PASSWORD=procom123
      - POSTGRESQL_DATABASE=procomdb
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=procom321
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG