# Generated by Django 2.1 on 2018-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20180809_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaprofile',
            name='is_mail_verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
