# Generated by Django 2.1 on 2018-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_metaprofile_is_mail_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaprofile',
            name='is_mail_verified',
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='is_mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
