# Generated by Django 2.1 on 2018-08-12 16:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20180810_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'address_line1': '', 'address_line2': '', 'address_name': '', 'country': 'INDIA', 'pincode': '', 'state': ''}),
        ),
    ]
