# Generated by Django 2.1 on 2018-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20180812_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainprofile',
            name='procom_secret',
            field=models.CharField(default='1912mnbxgudhdkdleldifne2839AEbdi', max_length=32),
            preserve_default=False,
        ),
    ]
