# Generated by Django 2.1 on 2018-08-21 00:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import jwt_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_mainprofile_procom_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=jwt_auth.models.address_field),
        ),
    ]
