# Generated by Django 2.1 on 2018-08-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0008_auto_20180821_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
